# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53fce956dd3ccdca7608a685b88b9c19767bc2ae9c2ab55cfa8e30566810975b7ba3b66eae697e7e761606ac92ecdf16207fce3d8ac7eee9d13144dfed8fe448

test:
  secret_key_base: 3a076f4c5cf8bdc754cecaa5d9099f39a981e6d25e41bda514e180ba07fd0bbf71941e90388d2f60bcf37e3225f30cccadd48c886afb2e9003a86575c5562b34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
